# Generated by Django 2.2.28 on 2022-11-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderd',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderd',
            new_name='ordered',
        ),
    ]
