# Generated by Django 2.2.28 on 2022-11-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221120_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_change_id',
            new_name='stripe_charge_id',
        ),
    ]
